# Generated by Django 5.2 on 2025-11-07 15:09

import apps.books.utilities
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=255)),
                ("anio_publicacion", models.IntegerField()),
                (
                    "isbn",
                    models.CharField(
                        max_length=15, validators=[apps.books.utilities.validate_isbn]
                    ),
                ),
            ],
        ),
    ]
