# Generated by Django 5.2 on 2025-11-07 15:54

import apps.books.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="isbn",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[apps.books.utilities.validate_isbn],
            ),
        ),
    ]
